[package]
name = "proof_of_function_relation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-poly-commit = { git = "ssh://git@github.com/geometryresearch/poly-commit.git" }
ark-ff = "0.3.0"
ark-poly = "0.3.0" 
ark-ec = "0.3.0"
ark-std = "0.3.0"
ark-marlin = "0.3.0"
ark-serialize = "0.3.0"
rand_core = {version = "0.6", default-features=false, features = ["getrandom"] }
ark-bn254 = "0.3.0"
rand = "0.8.4"
blake2 = { version = "0.9", default-features = false }
digest = { version = "0.9" }
zero_over_k = { path = "../zero_over_k" }

